@startuml

skinparam component {
  backgroundColor<<safety critical>> Aquamarine
  backgroundColor<<needs review>> DarkCyan
  fontColor<<needs review>> White
}

skinparam queue {
	backgroundColor<<safety critical>> Aquamarine
}

frame {
  node AdaptiveApplication {
    component ApplicationLogic
    interface "mw::log" as aralog1
    component "mw::log implementation" <<safety critical>> as aralog1_impl

    aralog1 - aralog1_impl
    ApplicationLogic --> aralog1 : verbose
    ApplicationLogic --> aralog1 : non-verbose
  }

  queue Ringbuffer1 <<safety critical>> as RB1
  database "/opt/<app>/etc/logging.json" as cfg1
  aralog1_impl ..> cfg1 : read config
}

frame {
  node SystemApplication {
    component SystemApplicationLogic
    interface "mw::log" as aralog2
    component "mw::log implementation" <<safety critical>> as aralog2_impl

    aralog2 - aralog2_impl
    SystemApplicationLogic --> aralog2 : verbose
    SystemApplicationLogic --> aralog2 : non-verbose
  }

  queue Ringbuffer2 <<safety critical>> as RB2
  database "/opt/<app>/etc/logging.json" as cfg2
  aralog2_impl ..> cfg2 : read config
}

note right of RB1
  Shared memory
  allocated by AdaptiveApplication
end note

aralog1_impl ..> RB1 : own
aralog2_impl ..> RB2 : own
aralog1_impl --> RB1 : write
aralog2_impl --> RB2 : write

database "class-id.json\n(MessageIDs)" as type_id

node "Datarouter" {

  component [Source Session 1] <<needs review>> as sourcesession1
  component [Source Session 2] <<needs review>> as sourcesession2

  component "NonVerboseHandler" as nvh {
    component "Filter" as nvfilter
    component "Pack" as nvpack

    type_id <.. nvfilter
    type_id <.. nvpack
    nvfilter --> nvpack
  }

  RB1 <-- sourcesession1 : read
  RB2 <-- sourcesession2 : read

  component "VerboseHandler" as vh {
    component "Pack" as vpack
    component "Filter" as vfilter

    vfilter --> vpack
  }

  component "FileTransferHandler" as fthandler {
  }

  component "DltLogServer" as dlt_out {
    component "Channel Assignment\n& Threshold Filter" as Demux
    component "DltLogChannel 1\n(UDP, per log-channels.json)" as dlt_ch1
    component "DltLogChannel 2\n(UDP, per log-channels.json)" as dlt_ch2
    component "... DltLogChannel N" as dlt_chN
    Demux -> dlt_ch1
    Demux -> dlt_ch2
    Demux -> dlt_chN
  }

  database "log-channels.json" as channels_cfg
  channels_cfg ..> Demux : configure channels\n& assignments

  component "SysedrHandler" as sysedr_handler {
  }
}

node "Persistent Storage" as persistent_storage {
  database "sysedr_N.dlt.gz" as sysedr_files
}

sysedr_handler --> persistent_storage

frame "DLT Channels (UDP multicast)" {
  boundary "DltLogChannel 1" as udp_1
  boundary "DltLogChannel 2" as udp_2
  boundary "DltLogChannel N" as udp_N
}

sourcesession1 ~~> vfilter : <verbose>
sourcesession2 ~~> vfilter : <verbose>
sourcesession1 ..> nvfilter : *
sourcesession2 ..> nvfilter : *
sourcesession1 --> sysedr_handler : <SysedrMessage>
sourcesession2 --> sysedr_handler : <SysedrMessage>
sourcesession1 --> fthandler : <FileTransfer>
sourcesession2 --> fthandler : <FileTransfer>

vpack -> Demux
nvpack -> Demux
fthandler -> Demux

dlt_ch1 -> udp_1
dlt_ch2 -> udp_2
dlt_chN -> udp_N

@enduml
