@startuml
title log message filtering based on log_level (Datarouter - Backend)

start

NOTE: This Flow diagram excludes the sequence for filtering DLT logs based on diagnostic job requests

:log_level_threshold = kVerbose (Default; hardcoded in socketserver_config.h);
:log_level = kInfo (Default; hardcoded);

    if (Parse class-id.json file (message ID table) success) then (yes)
    note left
         The class-id.json file is an output of the dlt_create_fibex generator
         containing unique message ids mapped to app_id, ctx_id and log_level pairs
         for message Types that needs to be traced out
    end note
            :Register message based on NvMsgDescriptor (message_id, app_id, ctx_id, log_level);
             NOTE: class-id.json
            :log_level = log_level for app_id ctx_id pair;
    note left
        The log_level is picked based on the inputs for the dlt_fibex_defenition
        generator for the respective Type that needs to be traced.
        E.g.: *_fibex.cpp
    end note
    else (no)
    endif

if (log-channels.json file found?) then (yes)
else (no)
     stop
endif

: Parse log-channels.json;
NOTE: log-channels.json

if (message thresholds set in log-channels.json?) then (yes)
   :log_level_threshold = message_threshold (log_level) for the respective ctx_id;
else (no)
   endif

if (log_level > logLevel_threshold) then (yes)
    :Drop the log message
    (Will NOT copy the DLT message
      to UDP socket buffers);
else (no)
    :Copy the DLT message to UDP socket buffers;
endif

stop
@enduml
